### ISSUE TITLE
Add discovery process to the website

### ISSUE THREAD

**Issue by Shaulbm** [Claro-Mentor/moovNowMVP#14]
Add the discovery page to the website
This page only encapsulates the discovery process mechanism (the actual creation of the discovery elements will be developed in a different issue)

**Comment by hadarbmdev** [comment]
Left tasks:
- To backlog: complete chat animations
- [In progress]: Get first question batch from server
- Save question answer to server
- To do: Handle what happens when batch is done: go to server  / show DONE
- Support multiple question types (requires design)
