### ISSUE TITLE
Select moov wizard looks very bad in these configurtations

### ISSUE THREAD

**Issue by Shaulbm** [Claro-Mentor/moovNowMVP#503]
I don't have a screenshot, but all the moovs are on top of one another.

![image.png](https://images.zenhubusercontent.com/6154661ee730b505f93cd71e/2b20b714-d76e-4a4e-99c5-1eda2351e230)

**Comment by NoamRivlin** [comment]
checked and only when zoom in is 250% zoom, I got this mobile view
not sure what led or what the display looked like in the of bug, but im not seeing it...
<img width="1634" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEJBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a0ff406f1187a6eecdb768d4ed686835d96da48/image.png" alt="image.png" />
