### ISSUE TITLE
when a moov is completed no stars feedback is presented on EndMoov view

### ISSUE THREAD

**Issue by Shaulbm** [Claro-Mentor/moovNowMVP#547]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmNmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--058ac1b2e4034708614cfabb2278ee629b084ac7/image.png)

**Comment by Shaulbm** [comment]
please recheck in production

**Comment by NoamRivlin** [comment]
im not a manager nor have a team in prod
