### ISSUE TITLE
My motivations looks bad in mobile view

### ISSUE THREAD

**Issue by Shaulbm** [Claro-Mentor/moovNowMVP#644]
<img width="358" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmxFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7218022030cdf91aa78fb69e8883b3e0b8563ff/image.png" alt="image.png" />

<img width="358" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnBFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--28d65be9de2a8cf1f30614c925687e2ed307d087/image.png" alt="image.png" />

**Comment by NoamRivlin** [comment]
done IMO
