### ISSUE TITLE
Allow the reseller to copy tokens as urls

### ISSUE THREAD

**Issue by Shaulbm** [Claro-Mentor/moovNowMVP#648]
1. copy the codes as a list  with enters
instead of copy the data to : "A","B","C"
copy the data like this (2 changes, no " and enter as a seperator):
A
B
C

2. another button to  get a list of tokens - get a list of
https://claro.one/discover?tokenBody=<accessToken>

Also - allow this copy for allocated tokens

Please notice to get the url from a config file (env.config.json)

**Comment by NoamRivlin** [comment]
done
