### ISSUE TITLE
TV - support different views and update availability

### ISSUE THREAD

**Issue by Shaulbm** [Claro-Mentor/moovNowMVP#660]
Page availability:
in case the account type is CLARO_COLLABORATE / CLARO_EXCEL and the user role is manager - or the user is a reseller -   

Support two views - 
1. no measurements (only team members and their drivers)
2. full (team members, drivers, each member energy, each driver energy)

for users type CLARO_COLLABORATE:
Only view 1 is available

for users type : CLARO_EXCEL
Both viewes are available

for resellers:
Boths viewes are available

View selection:
in case both views are available - let the user select what type he wants, default value is full. 
save the user selection in local storage (review example for usage of reseller_selected_org) - do not delete upon log off.

**Comment by NoamRivlin** [comment]
done
you said you wanted to present some icons instead of the drivers battery level.

**Comment by NoamRivlin** [comment]
saw the new icons instead of batteries. so is this issue done?
