### ISSUE TITLE
Change the main navigation bar UX 

### ISSUE THREAD

**Issue by Shaulbm** [Claro-Mentor/moovNowMVP#670]
Change the navigation bar UX according to the new design:
<img width="1421" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem5KQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eee7f2c20abbf31ad527b3fab3613ca9f24b00a9/image.png" alt="image.png" />

1. The new Menu should contain these options:
- Team
- Org State
- Claire
- My Drivers
- Drivers
- 

2. The remaining options should be in a menu (standard material menu) that is opened when hitting the name of the user (upper right corner - when LTR)
- Account Settings
- Log off

The menu sidebar should be always present and will take a permanent space from all the pages.

**Mobile View**
The menu should appear by hamburger option on the top left side (when LTR) - that will open the menu, the same as today and will contain the same option,
The personal menu will behave the same

**Notice**
- The current page should be marked in the menu, same as in the figma design.
- the menu should apply the same conditions as the current navigation bar (what option is presented to who).

**Comment by NoamRivlin** [comment]
we need a way for the user first name to be translated, maybe like its been done in TV.
right now I use user.firstName which isn't translated.
<img width="462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXJhQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f15519a7692f3f4395635c86a4e5f41845f28162/image.png" alt="image.png" />

**Comment by NoamRivlin** [comment]
DONE(?)
you still need to add translations to names
