### ISSUE TITLE
In ChatView - let the user open it with a new Question in the URL

### ISSUE THREAD

**Issue by Shaulbm** [Claro-Mentor/moovNowMVP#675]
When the url is:
/chatView?questionId=<someId>

Load as usual - but open a new chat and get the question content from the DB (getChatQuestion) - the returned question will be set as if the user typed it and hit submit

Notice that the screen for the user response should also be changed to alow "Go To Chat" button

**Comment by NoamRivlin** [comment]
i think it's done on my end.
instead of a setTimeout to mimic a db call,
it now needs to have an actual db call for a question by id to see that it works.
