### ISSUE TITLE
TSD - Very High / High should be highlighted

### ISSUE THREAD

**Issue by Shaulbm** [Claro-Mentor/moovNowMVP#676]
similiar to here:

<img width="152" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGF0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c8ed72d818f25dfac59174e9c310dd8bcc6d712/image.png" alt="image.png" />

**Comment by NoamRivlin** [comment]
gonna need more details, what should be highlighted? the tags?
<img width="1206" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0d1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75aae2531459c1574d91d2ef87fd9b9dbd548e05/image.png" alt="image.png" />
they're already blue in color so just add box shadow to them?

**Comment by NoamRivlin** [comment]
the whole card, without shadow

**Comment by NoamRivlin** [comment]
DONE
