### ISSUE TITLE
in chatView when getting a question from the url - send Analytics

### ISSUE THREAD

**Issue by Shaulbm** [Claro-Mentor/moovNowMVP#684]
when getting to chatView and getting questionId in the URL - raise analytics event with the question Id.

*Notice*
The analytics needs to be different whether the question was received from pulse checks or from tips.
Use the url variable as follows:
https://claro.one/chat?questionId=<qid>&origin=<originType>

where originType represents the source of the call (pulse/tip)

**Comment by NoamRivlin** [comment]
instead of creating a new branch with 675 content, I'll just add analytics to that branch, as it not part of main

**Comment by NoamRivlin** [comment]
checking out from 675, as its not in main yet

**Comment by NoamRivlin** [comment]
done - hoping i did it correctly

**Comment by Shaulbm** [comment]
for @Shaulbm verify to diffrentiate analyitics by origin
