### ISSUE TITLE
my motivations looking bad

### ISSUE THREAD

**Issue by Shaulbm** [Claro-Mentor/moovNowMVP#685]
<img width="1076" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekxyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5cc1a7ea2159e16af5888f7e8fb68919863416e9/image.png" alt="image.png" />

**Comment by NoamRivlin** [comment]
done with PR
