### ISSUE TITLE
Present possible questions in new chat 

### ISSUE THREAD

**Issue by Shaulbm** [Claro-Mentor/moovNowMVP#693]
When a user is presented with a "New Chat" page in the chat view, present him with possible questions.

The questions will have a list of subjects, each subject will have a list of possible questions.
Subject:
Id,
Name
Questions []

Question:
Id,
Content

When a user will click one of the questions the view will behave is if the user have submitted this question - and will present the page as usual.

Refer to this Figma:
https://www.figma.com/design/12WsfZKFtcN4lAaDAP7AvR/Claro-Mentor-%2F-Product?node-id=120-2&t=3qYduJy7XVNW5Fzd-0

Please also notice the different UX in this page and change accordingly/

The questions and subject will be provided by a BE function (getPossibleQuestionsForChat) - for now mock the response.

**Comment by NoamRivlin** [comment]
i named the branch -
feature/Issue-693-chat-newUI-suggestedQuestions
